#!/usr/bin/python
#coding: utf-8

import os, sys, json, base64, getpass, hashlib, cryptography, readline, shutil
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from faker import Faker as gen
from colorama import Fore, Back, Style
sys.path.append(os.path.abspath("assets"))
import vhacks

url = "http://localhost:4040/api"
ver = "v1.0.0"
key = AESGCM(AESGCM.generate_key(bit_length=256))

array = []
class auto(object):
	def __init__(self, options):
		self.options = sorted(options)
		
	def complete(self, text, state):
		if state == 0:
			if text:
				self.matches = [s for s in self.options if s and s.startswith(text)]
			else :
				self.matches = self.options[:]
		try:
			return self.matches[state]
		except IndexError:
			return None
def complete(array):
	completer = auto(array)
	readline.set_completer(completer.complete)
	readline.parse_and_bind("tab:complete")


# print(
#     json.dumps(
#         vhacks.Apps(url).addDataUsers("alvian", "alvianvian123"),
#         indent=2
#     )
# )

# print(
#     json.dumps(
#         vhacks.Apps(url).getDataUsers(),
#         indent=2
#     )
# )

vhacks.Console.log("!", "Note: This system is just for playing and feeling the sensation of being a hacker, but remember this system cannot be used to become a real hacker")
vhacks.Console.loading(f"Starting the vhacks console {ver}")

def saveData(**data):
    try:
        dataUser = json.loads(vhacks.System("assets/data").loadData("type:data"))
        for i in data:
            dataUser[i] = data[i]
        save = open("assets/data", "wb").write(
            vhacks.key.encrypt(
                vhacks.nonce,
                str(
                    json.dumps(
                        dataUser
                    )
                ).encode(),
                str("type:data").encode()
            )
        )
        return {
            "success": True,
            "msg": "Data saved successfully"
        }
    except KeyError:
        return {
            "success": False,
            "msg": "Failed to save data"
        }

def vhacksPrompt(user):
    modulePath = "~"
    open("assets/data", "wb").write(
        vhacks.key.encrypt(
            vhacks.nonce,
            str(
                json.dumps(
                    vhacks.Apps(vhacks.url).getDataWithUsername(user)["data"]
                )
            ).encode(),
            str("type:data").encode()
        )
    )
    loadData = json.loads(vhacks.System("assets/data").loadData("type:data"))
    #banner
    os.system("clear")
    print()
    print(f"      =[ vhacks {vhacks.ver}                                          ]")
    print(f"                                                                ]")
    print(f"\033[A+-- --=[ Your IP Address: {loadData['ipAddress']} (Don'ts share it)")
    print()
    vhacks.Console.log("!", "Do not force exit from the system, if you do your data will not be saved.")
    print()
    while True:
        try:
            loadData = json.loads(vhacks.System("assets/data").loadData("type:data"))
            prompt = str(input(f"vhacks.{user} ({modulePath}) > ")).split()
            if prompt[0] == "exit" or prompt[0] == "quit":
                loadData = json.loads(vhacks.System("assets/data").loadData("type:data"))
                saveDataUser = vhacks.Apps(vhacks.url).updateDataUsers(
                    username = loadData["username"],
                    password = loadData["password"],
                    otpCode = loadData["otpCode"],
                    ipAddress = loadData["ipAddress"],
                    macAddress = loadData["macAddress"],
                    vCoin = loadData["vCoin"],
                    vRam = loadData["vRam"],
                    vRamUsed = loadData["vRamUsed"],
                    vDisk = loadData["vDisk"],
                    vDiskUsed = loadData["vDiskUsed"],
                    vShell = loadData["vShell"],
                    vBin = loadData["vBin"]
                )
                if saveDataUser["success"] != True:
                    vhacks.Console.log("!", saveData["msg"])
                sys.exit()
            elif prompt[0] == "change":
                try:
                    if prompt[1] == "ipaddress" or prompt[1] == "-ia":
                        newIpAddress = gen().ipv4()
                        save = saveData(ipAddress=newIpAddress)
                        if save["success"]:
                            vhacks.Console.log("+", save["msg"])
                    else:
                        vhacks.Console.log("!", f"Unknown data '{prompt[1]}'")
                except IndexError:
                    print("Usage: change [data]")
            elif os.path.exists(f"home//bin/{prompt[0]}"):
                os.system(f"python home/bin/{prompt[0]}")
            else:
                vhacks.Console.log("!", f"Unknown command '{prompt[0]}'")
        except IndexError:
            pass
        except KeyboardInterrupt:
            loadData = json.loads(vhacks.System("assets/data").loadData("type:data"))
            saveDataUser = vhacks.Apps(vhacks.url).updateDataUsers(
                username = loadData["username"],
                password = loadData["password"],
                otpCode = loadData["otpCode"],
                ipAddress = loadData["ipAddress"],
                macAddress = loadData["macAddress"],
                vCoin = loadData["vCoin"],
                vRam = loadData["vRam"],
                vRamUsed = loadData["vRamUsed"],
                vDisk = loadData["vDisk"],
                vDiskUsed = loadData["vDiskUsed"],
                vShell = loadData["vShell"],
                vBin = loadData["vBin"]
            )
            print()
            sys.exit()

def main():
    if os.path.exists("assets/session"):
        try:
            dataSession = json.loads(
                base64.b64decode(
                    open("assets/session", "r").read().replace(base64.b64encode(str("type:session").encode()).decode(), "")
                ).decode()
            )
            vhacksPrompt(dataSession["username"])
        except json.decoder.JSONDecodeError:
            vhacks.Console.log("!", "Exit the session")
            while True:
                os.system("clear")
                print()
                print("\t\033[1;37m[ VHACKS.LOGIN ]")
                print()
                username = str(input("\033[1;34m[?] \033[1;37mUsername: "))
                if vhacks.Apps(vhacks.url).getDataWithUsername(username)["success"]:
                    break
                else:
                    vhacks.Console.log("!", "Username not registered")

            while True:
                os.system("clear")
                print()
                print("\t\033[1;37m[ VHACKS.LOGIN ]")
                print()
                print(f"\033[1;34m[?] \033[1;37mUsername: {username}")
                password = getpass.getpass("\033[1;34m[?] \033[1;37mPassword: ")
                if hashlib.md5(password.encode()).hexdigest() == vhacks.Apps(vhacks.url).getDataWithUsername(username)["data"]["password"]:
                    data = base64.b64encode(
                        str(
                            json.dumps({
                                "username": username,
                                "password": password
                            })
                        ).encode()
                    ).decode()
                    open("assets/session", "w").write(
                        f"{base64.b64encode(str('type:session').encode()).decode()}{data}"
                    )
                    vhacks.Console.log("+", "Signed in successfully")
                    break
                else:
                    vhacks.Console.log("!", "Incorrect password")
            vhacksPrompt(username)
    else:
        while True:
            os.system("clear")
            print()
            print(f"\t{Style.BRIGHT}[ VHACKS.REGISTER ]")
            print()
            servers = []
            print("List of all servers")
            print("===================")
            print()
            print("  No.     Server          Person")
            num = 0
            for server in vhacks.Apps(vhacks.url).getDataServer()["data"]:
                
                servers.append(server["name"])
                print(f"                          {server['vRamUsed']}")
                print(f"\033[A          {server['name']}")
                print(f"\033[A  {num}")
                num += 1
            print()
            newServer = str(input(f"{Style.BRIGHT + Fore.BLUE}[?] {Fore.WHITE}Select the server (Default: indonesia): ")).lower()
            if newServer == "":
                newServer = "indonesia"
                break
            try:
                try:
                    newServer = servers[int(newServer)]
                    break
                except IndexError:
                    vhacks.Console.log("!", f"Number {int(newServer)} does not exist")
            except ValueError:
                if newServer in str(servers):
                    break
                else:
                    vhacks.Console.log("!", f"Server name not found")

        while True:
            os.system("clear")
            print()
            print("\t\033[1;37m[ VHACKS.REGISTER ]")
            print()
            print("List of all servers")
            print("===================")
            print()
            print("  No.     Server          Person")
            num = 0
            for server in vhacks.Apps(vhacks.url).getDataServer()["data"]:
                print(f"                          {server['vRamUsed']}")
                print(f"\033[A          {server['name']}")
                print(f"\033[A  {num}")
                num += 1
            print()
            print(f"{Style.BRIGHT + Fore.BLUE}[?] {Fore.WHITE}Select the server (Default: indonesia): {newServer}")
            newUsername = str(input("\033[1;34m[?] \033[1;37mNew username: "))
            if vhacks.Apps(url).getDataWithUsername(newUsername)["success"] != True:
                break
            else:
                vhacks.Console.log("!", "Username already in use!")
        
        while True:
            os.system("clear")
            print()
            print("\t\033[1;37m[ VHACKS.REGISTER ]")
            print()
            print("List of all servers")
            print("===================")
            print()
            print("  No.     Server          Person")
            num = 0
            for server in vhacks.Apps(vhacks.url).getDataServer()["data"]:
                print(f"                          {server['vRamUsed']}")
                print(f"\033[A          {server['name']}")
                print(f"\033[A  {num}")
                num += 1
            print()
            print(f"{Style.BRIGHT + Fore.BLUE}[?] {Fore.WHITE}Select the server (Default: indonesia): {newServer}")
            print(f"\033[1;34m[?] \033[1;37mNew username: {newUsername}")
            newPassword = getpass.getpass("\033[1;34m[?] \033[1;37mNew Password: ")
            if len(newPassword) > 7:
                if vhacks.Apps(url).addDataUsers(newUsername, newPassword, newServer)["success"]:
                    getDataServer = vhacks.Apps(vhacks.url).getDataServer(name=newServer)["data"]
                    if vhacks.Apps(vhacks.url).updateDataServer(name=newServer, vRamUsed=int(getDataServer['vRamUsed'])+1)["success"]:
                        if os.path.exists(f"home/{newUsername}"):
                            shutil.rmtree(f"home/{newUsername}")
                        os.mkdir(f"home/{newUsername}")
                        data = base64.b64encode(
                            str(
                                json.dumps({
                                    "username": newUsername,
                                    "password": newPassword
                                })
                            ).encode()
                        ).decode()
                        open("assets/session", "w").write(
                            f"{base64.b64encode(str('type:session').encode()).decode()}{data}"
                        )
                        vhacks.Console.log("+", "Registered successfully")
                        break
                    else:
                        vhacks.Console.log("!", "Internal server error")
                else:
                    vhacks.Console.log("!", "Internal server error")
            else:
                vhacks.Console.log("!", "Password is too short")
        
        vhacksPrompt(newUsername)

if __name__ == "__main__":
    main()
